# Generated by Django 4.1.5 on 2023-01-21 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=55, null=True)),
                ('lastname', models.CharField(max_length=55, null=True)),
                ('number', models.CharField(max_length=55, null=True)),
            ],
        ),
    ]
