# Generated by Django 4.1.5 on 2023-01-21 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='rollno',
            field=models.CharField(max_length=55, null=True),
        ),
    ]
