# Generated by Django 4.1.5 on 2023-01-21 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_student_rollno'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Login',
            new_name='Signup',
        ),
    ]
