# Generated by Django 4.1.5 on 2023-01-21 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_rename_login_signup'),
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=55, null=True)),
                ('password', models.CharField(max_length=55, null=True)),
            ],
        ),
    ]
