# Generated by Django 4.1.5 on 2023-01-21 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_rename_password_signup_pass1_signup_pass2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signup',
            old_name='pass1',
            new_name='password1',
        ),
        migrations.RenameField(
            model_name='signup',
            old_name='pass2',
            new_name='password2',
        ),
        migrations.RenameField(
            model_name='signup',
            old_name='uname',
            new_name='username',
        ),
    ]
