# Generated by Django 4.1.5 on 2023-01-21 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_rename_email_login_pass1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signup',
            old_name='email',
            new_name='Email',
        ),
        migrations.RenameField(
            model_name='signup',
            old_name='pass1',
            new_name='password1',
        ),
        migrations.RenameField(
            model_name='signup',
            old_name='pass2',
            new_name='password2',
        ),
        migrations.RenameField(
            model_name='signup',
            old_name='uname',
            new_name='username',
        ),
    ]
