# Generated by Django 4.1.5 on 2023-01-21 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_rename_email_signup_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signup',
            old_name='password2',
            new_name='ConfirmPassword',
        ),
    ]
