# Generated by Django 4.1.5 on 2023-01-21 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_rename_password2_signup_confirmpassword'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signup',
            old_name='ConfirmPassword',
            new_name='password2',
        ),
    ]
