# Generated by Django 4.1.5 on 2023-01-21 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0012_rename_confirmpassword_signup_password2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signup',
            old_name='Email',
            new_name='email',
        ),
    ]
